security:
  app:
    jwtExpirationMs: 86400000
    jwtSecret: rookiesSecretKey

app :
  server: http://localhost:8080

default:
  app:
    email: quocminhh47@gmail.com
  url:
    image: https://res.cloudinary.com/duoih0eqa/image/upload/v1657297251/Untitled_xq9j9u.png

